apiVersion: v1
kind: Config
clusters:
  - name: production
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://172.17.0.51:6443

contexts:
  - name: admin@production
    context:
      cluster: production
      user: admin
      namespace: finance

users:
  - name: admin
    user:
      client-sertificate: /etc/kubernetes/pki/users/admin.crt
      client-key: /etc/kubernetes/pki/users/admin.key

# kubectl config --kubeconfig=/root/my-config use-context research

# Authorization Mechanisms
# 1. Node   2. ABAC  3. RBAC  4. Webhook
# NodeAuthorizer