# kubectl create secret generic <name> --from-literal=<key>=<value>

# echo -n "Password" | base64
# echo -n "cGFzc3dvcmQ=" | base64 --decode
# kubectl get po webapp-pod -o yaml > pod.yml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  password: cGFzc3dvcmQ=