apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage # use this with dynamic provisioning , no need to create PV for this
  resources:
    requests:
      storage: 500Mi